### ISSUE TITLE
Command args

### ISSUE THREAD

**Issue by ghost** [jdreeser/kanye#1]
Augment replacing system with arguments, allowing users to pass commands with arguments:
`!spin(erp)`
`!rhyme(lame)`
`!stat(str)`

**Comment by VHS420** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;qOydTVYW&#x2F;11-command-argument-passing"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> command argument passing</a>
