### ISSUE TITLE
Replace roll command with message replacement

### ISSUE THREAD

**Issue by ghost** [jdreeser/kanye#2]
Remove `!roll` command and instead replace any `!roll(1,20)` with roll result. Using #1 feature

**Comment by VHS420** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ARusKpvB&#x2F;12-change-roll-command-to-replacement"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> change roll command to replacement</a>
