### ISSUE TITLE
Evaluate roll arithmetic

### ISSUE THREAD

**Issue by ghost** [jdreeser/kanye#3]
scan messages containing '+', '-', '/', '*' for integers or subs. if subs exist, resolve them. evaluate resulting arithmetic

**Comment by VHS420** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;TfeTZgyr&#x2F;9-roll-arithmetic"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> roll arithmetic</a>

**Comment by jdreeser** [comment]
No longer part of the v0.1.0 milestone. Issue will be closed and reopened on https://github.com/jdreeser/arguer repo
