### ISSUE TITLE
Register and invoke character stats

### ISSUE THREAD

**Issue by ghost** [jdreeser/kanye#4]
Allow users to initialize character stats tied to their IRC nick, and allow them to call those stats as replacements: `I have a strength of !stat(str)`

depends on #1

**Comment by VHS420** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ksXWgXLl&#x2F;10-rpg-stat-tracking"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> rpg stat tracking</a>
